### ISSUE TITLE
Format or Example for key.json not provided

### ISSUE THREAD

**Issue by frankhinek** [VictorCoder123/ghost-storage#1]
Would it be possible to add an example key.json for AWS and Google to the README so that a user knows how to structure it?

**Comment by andreassolberg** [comment]
It is automatically generated from Google console when you create an service account.

**Comment by frankhinek** [comment]
What if you are only using AWS and not ever planning to use Google?  Then you wouldn't have the keys.json example.

**Comment by qishen** [comment]
Hi Frank, keys.json is only required for Google Storage, you don't need it when you are using Amazon Storage and the only thing you need is to update "accessKeyId", "secretAccessKey" in configuration.
